services:
  postgres:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=wormdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=wormuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
