blank_issues_enabled: false
contact_links:
  - name: Questions and Help
    url: https://github.com/bobbyquantum/inkweld/discussions
    about: Please ask and answer questions here in GitHub Discussions
  - name: Feature Ideas and Feedback
    url: https://github.com/bobbyquantum/inkweld/discussions/categories/ideas
    about: For feature ideas that aren't fully formed yet, start a discussion first
  - name: Project Documentation
    url: https://github.com/bobbyquantum/inkweld/tree/main/docs
    about: Check out the documentation before reporting issues
