spring:
  application:
    name: worm
  #  config:
  #properties    import: auth.yml
  mvc:
    ignore-trailing-slash: true
  session:
    store-type: mongodb
springdoc:
  api-docs:
    path: /api-docs
